[2025-06-17T18:10:25.755+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-17T18:10:25.775+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest manual__2025-06-17T18:10:24.743087+00:00 [queued]>
[2025-06-17T18:10:25.785+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest manual__2025-06-17T18:10:24.743087+00:00 [queued]>
[2025-06-17T18:10:25.786+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-06-17T18:10:25.800+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): spark_ingest> on 2025-06-17 18:10:24.743087+00:00
[2025-06-17T18:10:25.807+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=501) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-17T18:10:25.808+0000] {standard_task_runner.py:72} INFO - Started process 502 to run task
[2025-06-17T18:10:25.808+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ingest_csv_to_hive', 'spark_ingest', 'manual__2025-06-17T18:10:24.743087+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ETL_flow.py', '--cfg-path', '/tmp/tmpa2fewwvo']
[2025-06-17T18:10:25.810+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask spark_ingest
[2025-06-17T18:10:25.832+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-17T18:10:25.871+0000] {task_command.py:467} INFO - Running <TaskInstance: ingest_csv_to_hive.spark_ingest manual__2025-06-17T18:10:24.743087+00:00 [running]> on host b11ca03b7444
[2025-06-17T18:10:25.953+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_csv_to_hive' AIRFLOW_CTX_TASK_ID='spark_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-06-17T18:10:24.743087+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-17T18:10:24.743087+00:00'
[2025-06-17T18:10:25.954+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-17T18:10:25.970+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-17T18:10:25.971+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'set -o pipefail && spark-submit /opt/***/code/stage.py --master spark://spark-master:7077 --deploy-mode client --process-date 2025-06-17 2>&1']
[2025-06-17T18:10:25.980+0000] {subprocess.py:99} INFO - Output:
[2025-06-17T18:10:28.645+0000] {subprocess.py:106} INFO - usage: stage.py [-h] --process-date PROCESS_DATE
[2025-06-17T18:10:28.645+0000] {subprocess.py:106} INFO - stage.py: error: unrecognized arguments: --master spark://spark-master:7077 --deploy-mode client
[2025-06-17T18:10:28.694+0000] {subprocess.py:106} INFO - 25/06/17 18:10:28 INFO ShutdownHookManager: Shutdown hook called
[2025-06-17T18:10:28.696+0000] {subprocess.py:106} INFO - 25/06/17 18:10:28 INFO ShutdownHookManager: Deleting directory /tmp/spark-23172bdc-84e8-4c68-9036-731bbf5963c1
[2025-06-17T18:10:28.724+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-06-17T18:10:28.738+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-17T18:10:28.746+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_csv_to_hive, task_id=spark_ingest, run_id=manual__2025-06-17T18:10:24.743087+00:00, execution_date=20250617T181024, start_date=20250617T181025, end_date=20250617T181028
[2025-06-17T18:10:28.760+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-17T18:10:28.761+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task spark_ingest (Bash command failed. The command returned a non-zero exit code 2.; 502)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-17T18:10:28.795+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-17T18:10:28.816+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17T18:10:28.819+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
